Update python-tests.yml

diff --git a/.github/workflows/python-tests.yml b/.github/workflows/python-tests.yml
--- a/.github/workflows/python-tests.yml
+++ b/.github/workflows/python-tests.yml
@@ -28,7 +28,7 @@ jobs:
         id: pytest
         run: |
           source .venv/bin/activate
-          pytest --driver=chrome tests/ --html=report.html --self-contained-html || echo "Tests failed"
+          pytest tests/ --html=report.html --self-contained-html || echo "Tests failed"
 
       - name: Upload test report
         uses: actions/upload-artifact@v4
@@ -36,18 +36,14 @@ jobs:
           name: test-report
           path: report.html
 
-      - name: Check for screenshots folder
-        if: failure()
+      - name: Ensure screenshots directory exists
         run: |
-          if [ -d "screenshots" ]; then
-            echo "Screenshots directory found."
-          else
-            echo "No screenshots directory found. Skipping artifact upload."
+          if [ ! -d "screenshots" ]; then
+            echo "Screenshots directory not found. Creating empty directory."
+            mkdir -p screenshots
           fi
-        continue-on-error: true
 
       - name: Upload screenshots artifact
-        if: failure() && steps.check-and-upload-screenshots-if-tests-fail.outcome == 'success'
         uses: actions/upload-artifact@v4
         with:
           name: screenshots
